wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1643681125
    t:
      3:
      - 16
      4: 3.8.12
      5: 0.12.9
      8:
      - 3
      - 5
path:
  desc: null
  value: genres_mod.parquet
